using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class PlayerGroundCheck : MonoBehaviour
{
    PlayerController playerController;
    
    void Awake()
    {
        playerController = GetComponentInParent<PlayerController>();
    }

    void OnTriggerEnter(Collider other)
    {
        if(other .gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(true);
        
    }

    void OnTriggerExit(Collider other)
    {
        if(other .gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(false);
        

    }

    void OnTriggerStay(Collider other)
    {
        if(other .gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(true);  
        
    }

    void OnCollisionEnter(Collision collision){
        if(collision.gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(true);
        
    }
    void OnCollisionExit(Collision collision){
        if(collision.gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(false);
        
    }
    void OnCollisionStay(Collision collision){
        if(collision.gameObject == playerController.gameObject)
        {
            return;
        }
        
            playerController.SetGroundState(true);
        
    }
}
